import { describe, expect, test } from 'bun:test';
import {
	generateSQL,
	exportGenericSQL,
	exportMySQL,
	exportPostgres,
	exportSQLite,
	type Diagram
} from './index';
import { DB, type Field, type Relationship, type Table } from '../../data/constants';

function field(f: Partial<Field> & Pick<Field, 'id' | 'name' | 'type'>): Field {
	return {
		default: '',
		check: '',
		primary: false,
		unique: false,
		notNull: false,
		increment: false,
		comment: '',
		...f
	};
}

function table(t: Partial<Table> & Pick<Table, 'id' | 'name' | 'fields'>): Table {
	return {
		x: 0,
		y: 0,
		comment: '',
		indices: [],
		uniqueConstraints: [],
		color: '#175e7a',
		collapsed: false,
		locked: false,
		...t
	};
}

function rel(r: Partial<Relationship> & Pick<Relationship, 'startTableId' | 'startFieldId' | 'endTableId' | 'endFieldId'>): Relationship {
	return {
		id: 'r1',
		name: 'fk',
		cardinality: 'many_to_one',
		updateConstraint: 'No action',
		deleteConstraint: 'Cascade',
		...r
	};
}

/**
 * users(id PK auto-increment, email UNIQUE, name) with a composite unique
 * constraint and a plain index; posts.user_id -> users.id (ON DELETE CASCADE).
 */
function fixture(intType: string): Diagram {
	return {
		tables: [
			table({
				id: 'users',
				name: 'users',
				fields: [
					field({ id: 'u_id', name: 'id', type: intType, primary: true, notNull: true, increment: true }),
					field({ id: 'u_email', name: 'email', type: 'VARCHAR', size: 255, notNull: true, unique: true }),
					field({ id: 'u_name', name: 'name', type: 'VARCHAR', size: 100 })
				],
				indices: [{ name: 'idx_users_name', fields: ['name'], unique: false }],
				uniqueConstraints: [{ name: 'uq_users_email_name', fields: ['email', 'name'] }]
			}),
			table({
				id: 'posts',
				name: 'posts',
				fields: [
					field({ id: 'p_id', name: 'id', type: intType, primary: true, notNull: true }),
					field({ id: 'p_user', name: 'user_id', type: intType, notNull: true })
				]
			})
		],
		relationships: [
			rel({ startTableId: 'posts', startFieldId: 'p_user', endTableId: 'users', endFieldId: 'u_id' })
		]
	};
}

describe('PostgreSQL export', () => {
	const sql = exportPostgres(fixture('INTEGER'));

	test('emits PK, unique column, composite unique constraint and identity column', () => {
		expect(sql).toContain(
			'CREATE TABLE IF NOT EXISTS "users" (\n' +
				'\t"id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,\n' +
				'\t"email" VARCHAR(255) NOT NULL UNIQUE,\n' +
				'\t"name" VARCHAR(100),\n' +
				'\tPRIMARY KEY("id"),\n' +
				'\tCONSTRAINT "uq_users_email_name" UNIQUE ("email", "name")\n' +
				');'
		);
		expect(sql).not.toContain('AUTO_INCREMENT');
	});

	test('emits indices and ALTER TABLE foreign keys with ON UPDATE/DELETE', () => {
		expect(sql).toContain('CREATE INDEX "idx_users_name"\nON "users" ("name");');
		expect(sql).toContain(
			'ALTER TABLE "posts"\nADD FOREIGN KEY("user_id") REFERENCES "users"("id")\nON UPDATE NO ACTION ON DELETE CASCADE;'
		);
	});

	test('emits CREATE TYPE ... AS ENUM for diagram enums, before tables', () => {
		const diagram: Diagram = {
			tables: [
				table({
					id: 't',
					name: 'person',
					fields: [field({ id: 'f', name: 'feeling', type: 'mood', default: 'happy' })]
				})
			],
			relationships: [],
			enums: [{ id: 'e', name: 'mood', values: ['happy', 'sad', "it's ok"] }]
		};
		const out = exportPostgres(diagram);
		expect(out.startsWith(`CREATE TYPE "mood" AS ENUM (\n\t'happy',\n\t'sad',\n\t'it''s ok'\n);`)).toBe(true);
		// Columns reference the enum by the same quoted name.
		expect(out).toContain(`\t"feeling" "mood" DEFAULT 'happy'`);
		expect(out.indexOf('CREATE TYPE')).toBeLessThan(out.indexOf('CREATE TABLE'));
	});

	test('emits composite CREATE TYPE with COMMENT ON TYPE for custom types', () => {
		const diagram: Diagram = {
			tables: [],
			relationships: [],
			types: [
				{
					id: 'ty',
					name: 'address',
					comment: 'Postal address',
					fields: [
						field({ id: 'a1', name: 'street', type: 'VARCHAR', size: 100 }),
						field({ id: 'a2', name: 'zip', type: 'INTEGER' })
					]
				}
			]
		};
		expect(exportPostgres(diagram)).toBe(
			'CREATE TYPE "address" AS (\n\t"street" VARCHAR(100),\n\t"zip" INTEGER\n);\n\n' +
				`COMMENT ON TYPE "address" IS 'Postal address';\n`
		);
	});

	test('emits COMMENT ON TABLE / COLUMN with escaped quotes', () => {
		const d = fixture('INTEGER');
		d.tables[0].comment = "User's accounts";
		d.tables[0].fields[1].comment = 'Login e-mail';
		const out = exportPostgres(d);
		expect(out).toContain(`COMMENT ON TABLE "users" IS 'User''s accounts';`);
		expect(out).toContain(`COMMENT ON COLUMN "users"."email" IS 'Login e-mail';`);
	});

	test('quotes defaults by the type\'s hasQuotes flag', () => {
		const out = exportPostgres({
			tables: [
				table({
					id: 't',
					name: 't',
					fields: [
						field({ id: 'a', name: 'code', type: 'VARCHAR', size: 10, default: '123' }),
						field({ id: 'b', name: 'qty', type: 'INTEGER', default: '5' }),
						field({ id: 'c', name: 'active', type: 'BOOLEAN', default: 'true' })
					]
				})
			],
			relationships: []
		});
		expect(out).toContain(`"code" VARCHAR(10) DEFAULT '123'`);
		expect(out).toContain('"qty" INTEGER DEFAULT 5');
		expect(out).toContain('"active" BOOLEAN DEFAULT true');
	});
});

describe('MySQL export', () => {
	const sql = exportMySQL(fixture('INTEGER'));

	test('emits PK, unique column, composite unique constraint and AUTO_INCREMENT', () => {
		expect(sql).toContain(
			'CREATE TABLE IF NOT EXISTS `users` (\n' +
				'\t`id` INTEGER NOT NULL AUTO_INCREMENT,\n' +
				'\t`email` VARCHAR(255) NOT NULL UNIQUE,\n' +
				'\t`name` VARCHAR(100),\n' +
				'\tPRIMARY KEY(`id`),\n' +
				'\tCONSTRAINT `uq_users_email_name` UNIQUE (`email`, `name`)\n' +
				');'
		);
	});

	test('emits indices and ALTER TABLE foreign keys with ON UPDATE/DELETE', () => {
		expect(sql).toContain('CREATE INDEX `idx_users_name`\nON `users` (`name`);');
		expect(sql).toContain(
			'ALTER TABLE `posts`\nADD FOREIGN KEY(`user_id`) REFERENCES `users`(`id`)\nON UPDATE NO ACTION ON DELETE CASCADE;'
		);
	});

	test('emits inline table and column comments', () => {
		const d = fixture('INTEGER');
		d.tables[0].comment = 'User accounts';
		d.tables[0].fields[1].comment = 'Login e-mail';
		const out = exportMySQL(d);
		expect(out).toContain("`email` VARCHAR(255) NOT NULL UNIQUE COMMENT 'Login e-mail'");
		expect(out).toContain(") COMMENT='User accounts';");
	});
});

describe('SQLite export', () => {
	const sql = exportSQLite(fixture('INTEGER'));

	test('emits PK and unique constraints without AUTO_INCREMENT', () => {
		expect(sql).toContain(
			'CREATE TABLE IF NOT EXISTS "users" (\n' +
				'\t"id" INTEGER NOT NULL,\n' +
				'\t"email" TEXT NOT NULL UNIQUE,\n' +
				'\t"name" TEXT,\n' +
				'\tPRIMARY KEY("id"),\n' +
				'\tCONSTRAINT "uq_users_email_name" UNIQUE ("email", "name")\n' +
				');'
		);
		expect(sql).not.toContain('AUTO_INCREMENT');
		expect(sql).not.toContain('ALTER TABLE');
	});

	test('emits indices and inline foreign keys with ON UPDATE/DELETE', () => {
		expect(sql).toContain('CREATE INDEX IF NOT EXISTS "idx_users_name"\nON "users" ("name");');
		expect(sql).toContain(
			'CREATE TABLE IF NOT EXISTS "posts" (\n' +
				'\t"id" INTEGER NOT NULL,\n' +
				'\t"user_id" INTEGER NOT NULL,\n' +
				'\tPRIMARY KEY("id"),\n' +
				'\tFOREIGN KEY ("user_id") REFERENCES "users"("id")\n' +
				'\tON UPDATE NO ACTION ON DELETE CASCADE\n' +
				');'
		);
	});
});

describe('Generic export', () => {
	const sql = exportGenericSQL(fixture('INT'));

	test('emits PK and unique constraints without engine-specific increment syntax', () => {
		expect(sql).toContain(
			'CREATE TABLE IF NOT EXISTS "users" (\n' +
				'\t"id" INT NOT NULL,\n' +
				'\t"email" VARCHAR(255) NOT NULL UNIQUE,\n' +
				'\t"name" VARCHAR(100),\n' +
				'\tPRIMARY KEY("id"),\n' +
				'\tCONSTRAINT "uq_users_email_name" UNIQUE ("email", "name")\n' +
				');'
		);
		expect(sql).not.toContain('AUTO_INCREMENT');
		expect(sql).not.toContain('IDENTITY');
	});

	test('emits indices and ALTER TABLE foreign keys', () => {
		expect(sql).toContain('CREATE INDEX "idx_users_name"\nON "users" ("name");');
		expect(sql).toContain(
			'ALTER TABLE "posts"\nADD FOREIGN KEY("user_id") REFERENCES "users"("id")\nON UPDATE NO ACTION ON DELETE CASCADE;'
		);
	});
});

describe('composite foreign keys', () => {
	const diagram: Diagram = {
		tables: [
			table({
				id: 'parent',
				name: 'parent',
				fields: [
					field({ id: 'x', name: 'x', type: 'INTEGER', primary: true }),
					field({ id: 'y', name: 'y', type: 'INTEGER', primary: true })
				]
			}),
			table({
				id: 'child',
				name: 'child',
				fields: [
					field({ id: 'a', name: 'a', type: 'INTEGER' }),
					field({ id: 'b', name: 'b', type: 'INTEGER' })
				]
			})
		],
		relationships: [
			rel({
				startTableId: 'child',
				startFieldId: 'a',
				endTableId: 'parent',
				endFieldId: 'x',
				fields: [
					{ startFieldId: 'a', endFieldId: 'x' },
					{ startFieldId: 'b', endFieldId: 'y' }
				]
			})
		]
	};

	test('Postgres lists every column pair', () => {
		expect(exportPostgres(diagram)).toContain('ADD FOREIGN KEY("a", "b") REFERENCES "parent"("x", "y")');
	});

	test('SQLite inlines every column pair', () => {
		expect(exportSQLite(diagram)).toContain('FOREIGN KEY ("a", "b") REFERENCES "parent"("x", "y")');
	});
});

describe('generateSQL dispatch', () => {
	const d = fixture('INTEGER');

	test('routes each engine to its exporter', () => {
		expect(generateSQL(DB.POSTGRES, d)).toBe(exportPostgres(d));
		expect(generateSQL(DB.MYSQL, d)).toBe(exportMySQL(d));
		expect(generateSQL(DB.SQLITE, d)).toBe(exportSQLite(d));
		expect(generateSQL(DB.GENERIC, d)).toBe(exportGenericSQL(d));
	});

	test('MariaDB uses MySQL syntax; MSSQL/Oracle fall back to generic', () => {
		expect(generateSQL(DB.MARIADB, d)).toBe(exportMySQL(d));
		expect(generateSQL(DB.MSSQL, d)).toBe(exportGenericSQL(d));
		expect(generateSQL(DB.ORACLESQL, d)).toBe(exportGenericSQL(d));
	});
});
