import type { Field, Table } from '$lib/data/constants';
import {
	escapeQuotes,
	exportFieldComment,
	parseDefault,
	uniqueConstraintClause,
	getFkColumnNames,
	type Diagram
} from './shared';

/**
 * Map a generic field type to a PostgreSQL type string.
 * Handles SERIAL for auto-increment integer types, array notation for SET,
 * timestamptz, and sized types.
 */
function pgType(field: Field): string {
	// Auto-increment integer types become SERIAL variants.
	if (field.increment) {
		switch (field.type.toUpperCase()) {
			case 'SMALLINT':
				return 'SMALLSERIAL';
			case 'INT':
			case 'INTEGER':
				return 'SERIAL';
			case 'BIGINT':
				return 'BIGSERIAL';
		}
	}

	switch (field.type.toUpperCase()) {
		case 'ENUM':
			return field.values && field.values.length > 0
				? `TEXT CHECK("${field.name}" IN (${field.values.map((v) => `'${escapeQuotes(String(v))}'`).join(', ')}))`
				: 'TEXT';
		case 'SET':
			return 'TEXT[]';
		case 'TIMESTAMP':
			return 'TIMESTAMPTZ';
		case 'DATETIME':
			return 'TIMESTAMP';
		case 'BINARY':
			return field.size ? `BIT(${field.size})` : 'BYTEA';
		case 'VARBINARY':
			return field.size ? `BIT VARYING(${field.size})` : 'BYTEA';
		case 'BLOB':
			return 'BYTEA';
		case 'JSON':
			return 'JSONB';
		case 'DOUBLE':
			return 'DOUBLE PRECISION';
		case 'BOOLEAN':
			return 'BOOLEAN';
		default: {
			const typeLower = field.type.toLowerCase();
			if (field.size !== undefined && field.size !== '' && field.size !== null) {
				return `${typeLower}(${field.size})`;
			}
			return typeLower;
		}
	}
}

/**
 * Format a single field definition for PostgreSQL.
 */
function formatField(field: Field): string {
	const comment = exportFieldComment(field.comment);
	const typeStr = pgType(field);

	// If the type already includes a CHECK (for ENUM), skip additional modifiers
	// that would conflict.
	const isEnumType = field.type.toUpperCase() === 'ENUM';

	let def = `${comment}\t"${field.name}" ${typeStr}`;

	if (field.notNull) {
		def += ' NOT NULL';
	}
	if (field.unique) {
		def += ' UNIQUE';
	}
	// SERIAL types already imply auto-increment; skip the keyword for non-serial increments.
	if (
		field.increment &&
		!['SMALLINT', 'INT', 'INTEGER', 'BIGINT'].includes(field.type.toUpperCase())
	) {
		def += ' GENERATED BY DEFAULT AS IDENTITY';
	}

	const defaultVal = parseDefault(field);
	if (field.default !== '' && field.default !== undefined && field.default !== null) {
		def += ` DEFAULT ${defaultVal}`;
	}

	if (!isEnumType && field.check && field.check !== '') {
		def += ` CHECK(${field.check})`;
	}

	return def;
}

/**
 * Generate a CREATE TABLE statement for a single table in PostgreSQL syntax,
 * followed by COMMENT ON statements and index creation.
 */
function formatTable(table: Table): string {
	const fields = table.fields.map(formatField).join(',\n');

	const primaryKeys = table.fields.filter((f) => f.primary);
	const pkClause =
		primaryKeys.length > 0
			? `,\n\tPRIMARY KEY(${primaryKeys.map((f) => `"${f.name}"`).join(', ')})`
			: '';

	const ucClause = uniqueConstraintClause(table, (s) => `"${s}"`);

	let sql = `CREATE TABLE IF NOT EXISTS "${table.name}" (\n${fields}${pkClause}${ucClause}\n);\n`;

	// Table and column comments via COMMENT ON.
	const comments: string[] = [];
	if (table.comment && table.comment.trim() !== '') {
		comments.push(
			`COMMENT ON TABLE "${table.name}" IS '${escapeQuotes(table.comment)}';`
		);
	}
	for (const field of table.fields) {
		if (field.comment && field.comment.trim() !== '') {
			comments.push(
				`COMMENT ON COLUMN "${table.name}"."${field.name}" IS '${escapeQuotes(field.comment)}';`
			);
		}
	}
	if (comments.length > 0) {
		sql += '\n' + comments.join('\n') + '\n';
	}

	// Indices
	if (table.indices && table.indices.length > 0) {
		const indexStatements = table.indices
			.map(
				(idx) =>
					`CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX "${idx.name}"\nON "${table.name}" (${idx.fields.map((f) => `"${f}"`).join(', ')});`
			)
			.join('\n');
		sql += '\n' + indexStatements + '\n';
	}

	return sql;
}

/**
 * Generate a complete PostgreSQL SQL export for the given diagram.
 * Includes CREATE TABLE statements, COMMENT ON statements, indices,
 * and ALTER TABLE ADD FOREIGN KEY statements.
 */
export function exportPostgres(diagram: Diagram): string {
	const tableStatements = diagram.tables.map(formatTable).join('\n');

	const fkStatements = diagram.relationships
		.map((r) => {
			const startTable = diagram.tables.find((t) => t.id === r.startTableId);
			const endTable = diagram.tables.find((t) => t.id === r.endTableId);
			if (!startTable || !endTable) return '';

			const { startColumns, endColumns } = getFkColumnNames(r, startTable, endTable);
			if (startColumns.some((c) => !c) || endColumns.some((c) => !c)) return '';

			return (
				`ALTER TABLE "${startTable.name}"\n` +
				`ADD FOREIGN KEY(${startColumns.map((c) => `"${c}"`).join(', ')}) ` +
				`REFERENCES "${endTable.name}"(${endColumns.map((c) => `"${c}"`).join(', ')})\n` +
				`ON UPDATE ${r.updateConstraint.toUpperCase()} ON DELETE ${r.deleteConstraint.toUpperCase()};`
			);
		})
		.filter(Boolean)
		.join('\n');

	return [tableStatements.trim(), fkStatements.trim()].filter(Boolean).join('\n\n') + '\n';
}
