import { DB, type CustomType, type EnumType, type Field, type Table } from '../../data/constants';
import {
	escapeQuotes,
	exportFieldComment,
	getTypeInfo,
	parseDefault,
	shouldEmitCheck,
	uniqueConstraintClause,
	getFkColumnNames,
	type Diagram
} from './shared';

// Optional keys present on diagrams imported from drawdb.app JSON that the
// desktop `Field`/`Table` types don't declare yet (drawdb-main postgres.js:36-39,48).
type PgField = Field & { isArray?: boolean };
type PgTable = Table & { inherits?: string[] };

/**
 * Map a field type to a PostgreSQL type string.
 * Native Postgres types (the diagram's own type list) are emitted verbatim like
 * the web original (drawdb-main/src/utils/exportSQL/postgres.js:45-48); names of
 * diagram enums/composite types are quoted to match their `CREATE TYPE "name"`;
 * types carried over from other dialects (ENUM, SET, DATETIME, BLOB, …) are
 * mapped to a Postgres equivalent.
 */
function pgType(field: Field, customTypeNames: Set<string>): string {
	if (customTypeNames.has(field.type)) {
		return `"${field.type}"`;
	}

	switch (field.type.toUpperCase()) {
		case 'ENUM':
			return field.values && field.values.length > 0
				? `TEXT CHECK("${field.name}" IN (${field.values.map((v) => `'${escapeQuotes(String(v))}'`).join(', ')}))`
				: 'TEXT';
		case 'SET':
			return 'TEXT[]';
		case 'DATETIME':
			return 'TIMESTAMP';
		case 'BINARY':
			return field.size ? `BIT(${field.size})` : 'BYTEA';
		case 'VARBINARY':
			return field.size ? `BIT VARYING(${field.size})` : 'BYTEA';
		case 'BLOB':
			return 'BYTEA';
		case 'DOUBLE':
			return 'DOUBLE PRECISION';
		default: {
			const info = getTypeInfo(DB.POSTGRES, field.type);
			const sizable = info ? info.isSized || info.hasPrecision : true;
			if (sizable && field.size !== undefined && field.size !== '' && field.size !== null) {
				return `${field.type}(${field.size})`;
			}
			return field.type;
		}
	}
}

/**
 * Format a single field definition for PostgreSQL.
 */
function formatField(field: PgField, customTypeNames: Set<string>): string {
	const comment = exportFieldComment(field.comment);
	const typeStr = pgType(field, customTypeNames);

	// If the type already includes a CHECK (for ENUM), skip additional modifiers
	// that would conflict.
	const isEnumType = field.type.toUpperCase() === 'ENUM';

	let def = `${comment}\t"${field.name}" ${typeStr}`;

	if (field.isArray) {
		def += ' ARRAY';
	}
	if (field.notNull) {
		def += ' NOT NULL';
	}
	if (field.unique) {
		def += ' UNIQUE';
	}
	// WHY: the web original uses an identity column for every auto-increment field
	// (drawdb-main postgres.js:50). SERIAL-family types already auto-increment, so
	// adding IDENTITY to them would be rejected by Postgres.
	if (field.increment && !/^(SMALL|BIG)?SERIAL$/i.test(field.type)) {
		def += ' GENERATED BY DEFAULT AS IDENTITY';
	}

	if (String(field.default ?? '').trim() !== '') {
		def += ` DEFAULT ${parseDefault(field, DB.POSTGRES)}`;
	}

	if (!isEnumType && shouldEmitCheck(field, DB.POSTGRES)) {
		def += ` CHECK(${field.check})`;
	}

	return def;
}

/**
 * `CREATE TYPE ... AS ENUM` for each diagram enum
 * (drawdb-main/src/utils/exportSQL/postgres.js:12-19).
 */
function formatEnum(e: EnumType): string {
	return `CREATE TYPE "${e.name}" AS ENUM (\n${(e.values || [])
		.map((v) => `\t'${escapeQuotes(String(v))}'`)
		.join(',\n')}\n);`;
}

/**
 * Composite `CREATE TYPE ... AS (...)` plus optional `COMMENT ON TYPE` for each
 * diagram custom type (drawdb-main/src/utils/exportSQL/postgres.js:21-32).
 * Deviation: the type and attribute names are quoted (web leaves them bare but
 * quotes the COMMENT ON TYPE target, which breaks for mixed-case names).
 */
function formatCustomType(type: CustomType, customTypeNames: Set<string>): string {
	const attrs = (type.fields || [])
		.map((f) => `\t"${f.name}" ${pgType(f, customTypeNames)}`)
		.join(',\n');
	let sql = `CREATE TYPE "${type.name}" AS (\n${attrs}\n);`;
	if (type.comment && type.comment.trim() !== '') {
		sql += `\n\nCOMMENT ON TYPE "${type.name}" IS '${escapeQuotes(type.comment)}';`;
	}
	return sql;
}

/**
 * Generate a CREATE TABLE statement for a single table in PostgreSQL syntax,
 * followed by COMMENT ON statements and index creation.
 */
function formatTable(table: PgTable, customTypeNames: Set<string>): string {
	const fields = table.fields.map((f) => formatField(f, customTypeNames)).join(',\n');

	const primaryKeys = table.fields.filter((f) => f.primary);
	const pkClause =
		primaryKeys.length > 0
			? `,\n\tPRIMARY KEY(${primaryKeys.map((f) => `"${f.name}"`).join(', ')})`
			: '';

	const ucClause = uniqueConstraintClause(table, (s) => `"${s}"`);

	const inheritsClause =
		Array.isArray(table.inherits) && table.inherits.length > 0
			? `\n) INHERITS (${table.inherits.map((parent) => `"${parent}"`).join(', ')})`
			: '\n)';

	const parts = [
		`CREATE TABLE IF NOT EXISTS "${table.name}" (\n${fields}${pkClause}${ucClause}${inheritsClause};`
	];

	// Table and column comments via COMMENT ON.
	const comments: string[] = [];
	if (table.comment && table.comment.trim() !== '') {
		comments.push(
			`COMMENT ON TABLE "${table.name}" IS '${escapeQuotes(table.comment)}';`
		);
	}
	for (const field of table.fields) {
		if (field.comment && field.comment.trim() !== '') {
			comments.push(
				`COMMENT ON COLUMN "${table.name}"."${field.name}" IS '${escapeQuotes(field.comment)}';`
			);
		}
	}
	if (comments.length > 0) {
		parts.push(comments.join('\n'));
	}

	// Indices
	if (table.indices && table.indices.length > 0) {
		parts.push(
			table.indices
				.map(
					(idx) =>
						`CREATE ${idx.unique ? 'UNIQUE ' : ''}INDEX "${idx.name}"\nON "${table.name}" (${idx.fields.map((f) => `"${f}"`).join(', ')});`
				)
				.join('\n')
		);
	}

	// WHY: statement grouping/blank lines follow drawdb-main postgres.js:93-99.
	return parts.join('\n\n');
}

/**
 * Generate a complete PostgreSQL SQL export for the given diagram.
 * Order follows drawdb-main/src/utils/exportSQL/postgres.js:127-135: enum
 * types, composite types, CREATE TABLE (+ COMMENT ON, indices), then
 * ALTER TABLE ADD FOREIGN KEY statements.
 */
export function exportPostgres(diagram: Diagram): string {
	const enums = diagram.enums || [];
	const types = diagram.types || [];
	const customTypeNames = new Set<string>([
		...enums.map((e) => e.name),
		...types.map((t) => t.name)
	]);

	const enumStatements = enums.map(formatEnum).join('\n\n');
	const typeStatements = types.map((t) => formatCustomType(t, customTypeNames)).join('\n\n');
	const tableStatements = diagram.tables
		.map((t) => formatTable(t, customTypeNames))
		.join('\n\n');

	const fkStatements = diagram.relationships
		.map((r) => {
			const startTable = diagram.tables.find((t) => t.id === r.startTableId);
			const endTable = diagram.tables.find((t) => t.id === r.endTableId);
			if (!startTable || !endTable) return '';

			const { startColumns, endColumns } = getFkColumnNames(r, startTable, endTable);
			if (startColumns.some((c) => !c) || endColumns.some((c) => !c)) return '';

			return (
				`ALTER TABLE "${startTable.name}"\n` +
				`ADD FOREIGN KEY(${startColumns.map((c) => `"${c}"`).join(', ')}) ` +
				`REFERENCES "${endTable.name}"(${endColumns.map((c) => `"${c}"`).join(', ')})\n` +
				`ON UPDATE ${r.updateConstraint.toUpperCase()} ON DELETE ${r.deleteConstraint.toUpperCase()};`
			);
		})
		.filter(Boolean)
		.join('\n');

	return (
		[enumStatements, typeStatements, tableStatements, fkStatements]
			.map((s) => s.trim())
			.filter(Boolean)
			.join('\n\n') + '\n'
	);
}
